#!/bin/bash -ex

. ../../venvs/testy/bin/activate
latest=true ./vagrant-platform up
./gen-testy-config > testy_config.json
testy_config=`readlink -f testy_config.json`
(cd testy && ./runtesty.py -f suites/standard_suite_local.json -f $testy_config)
./vagrant-platform destroy -f
